# Generated by Django 4.1.4 on 2022-12-10 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('ID_number', models.CharField(max_length=10)),
                ('staff_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.stafftype')),
            ],
        ),
    ]
